"""app_abdelhafidh_mahouel.py - Project script.

Author: Abdelhafidh Mahouel
Date: 2026-01

Practice key Python skills:
- docstring comments used at the start of each module and function
- pathlib for cross-platform file paths
- creating and writing files
- type hints (explicit types)
- logging (preferred over print)
- repetition patterns:
  - for year in range(...)
  - for item in list
  - list comprehension
  - while loop
- standard Python entry point pattern (if __name__ == "__main__":)

This script automates the creation of multiple text files.
These files are intended to be committed to Git as evidence of automation.
"""

# === DECLARE IMPORTS (BRING IN FREE CODE) ===

import logging
import time
from pathlib import Path
from typing import Final

# External (must be listed in pyproject.toml)
from datafun_toolkit.logger import get_logger, log_header

# === CONFIGURE LOGGER ONCE PER MODULE (FILE) ===

LOG: logging.Logger = get_logger("P02", level="DEBUG")

# === DECLARE SOME GLOBAL VARIABLES ===

ROOT_DIR: Final[Path] = Path.cwd()

REGIONS: Final[list[str]] = [
    "North America",
    "South America",
    "Europe",
    "Asia",
    "Africa",
    "Oceania",
    "Middle East",
]

NAME_PREFIX: Final[str] = "abdelhafidh_mahouel"


# === HELPER FUNCTION THAT WRITES A FILE AND LOGS IT ===


def write_text_file(path: Path, content: str) -> None:
    """Write content to a text file (overwriting if it exists).

    Arguments:
        path: Full path to the file to create/write.
        content: Text content to write.

    Returns:
        None
    """
    path.write_text(content, encoding="utf-8")
    LOG.info("WROTE file: %s", path.name)


# === REPETITION FUNCTION 1: FOR EACH IN NUMERIC RANGE ===


def create_files_from_numeric_range() -> None:
    """Create one file per year for years 2023 to 2026 inclusive.

    Arguments: None
    Returns:   None
    """
    LOG.info("START FUNCTION 1: create_files_from_numeric_range()")

    start_year: int = 2023
    end_year: int = 2026

    LOG.info("Starting year: %s", start_year)
    LOG.info("Ending year: %s", end_year)

    for year in range(start_year, end_year + 1):
        filename: str = f"{NAME_PREFIX}_year_{year}.txt"
        path: Path = ROOT_DIR / filename
        content: str = (
            f"Automated yearly report\nAuthor: Abdelhafidh Mahouel\nYear: {year}\n"
        )
        write_text_file(path, content)


# === REPETITION FUNCTION 2: FOR ITEM IN LIST ===


def create_files_from_list() -> None:
    """Create one file for each world region in a list.

    Arguments: None
    Returns:   None
    """
    LOG.info("START FUNCTION 2: create_files_from_list()")
    LOG.info("Region list: %s", REGIONS)

    for region in REGIONS:
        safe_region: str = region.lower().replace(" ", "_")
        filename: str = f"{NAME_PREFIX}_region_{safe_region}.txt"
        path: Path = ROOT_DIR / filename
        content: str = (
            "Region file (automated)\n"
            f"Region: {region}\n"
            "Generated by: Abdelhafidh Mahouel\n"
        )
        write_text_file(path, content)


# === REPETITION FUNCTION 3: LIST COMPREHENSION ===


def create_files_using_list_comprehension() -> None:
    """Transform a list using list comprehension, then create one file per transformed item.

    Arguments: None
    Returns:   None
    """
    LOG.info("START FUNCTION 3: create_files_using_list_comprehension()")
    LOG.info("WHY: Use list comprehension to transform one list into another list.")

    region_tags: list[str] = [region.upper().replace(" ", "_") for region in REGIONS]
    LOG.info("Transformed region tags: %s", region_tags)

    for tag in region_tags:
        filename: str = f"{NAME_PREFIX}_tag_{tag.lower()}.txt"
        path: Path = ROOT_DIR / filename
        content: str = (
            "Transformed region tag file (automated)\n"
            f"Tag: {tag}\n"
            "Original source: REGIONS list\n"
        )
        write_text_file(path, content)


# === REPETITION FUNCTION 4: WHILE LOOP (PERIODIC) ===


def create_files_periodically() -> None:
    """Create a small number of files with a delay between each creation.

    Creates at least 5 and fewer than 25 files.

    Arguments: None
    Returns:   None
    """
    LOG.info("START FUNCTION 4: create_files_periodically()")
    LOG.info("WHY: Use while loop for repetitive tasks with a delay.")

    wait_seconds: int = 1
    count: int = 7  # at least 5, less than 25

    LOG.info("Waiting seconds between files: %s", wait_seconds)
    LOG.info("Number of files to create: %s", count)

    i: int = 1
    while i <= count:
        filename: str = f"{NAME_PREFIX}_periodic_{i:02d}.txt"
        path: Path = ROOT_DIR / filename
        content: str = (
            "Periodic file creation (automated)\n"
            f"File number: {i}\n"
            f"Delay seconds: {wait_seconds}\n"
        )
        write_text_file(path, content)

        LOG.info("Waiting %s seconds before next file...", wait_seconds)
        time.sleep(wait_seconds)
        i += 1


# === MAIN FUNCTION ===


def main() -> None:
    """Entry point for the script.

    Creates files as visible artifacts which will be committed to Git.

    Arguments: None
    Returns:   None
    """
    log_header(LOG, "Automation: Creating Files with Repetition Patterns")
    LOG.info("START main()")

    create_files_from_numeric_range()
    create_files_from_list()
    create_files_using_list_comprehension()
    create_files_periodically()

    LOG.info("END main()")


# === CONDITIONAL EXECUTION GUARD ===

if __name__ == "__main__":
    main()
